name: Test-all
on: push
jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setting up JDK 1.8 (default JDK)
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Temp - Build w. maven just so I can test if ghub-actions works w. local repos (no caching)
      - run: mvn test
